### ISSUE TITLE
AttributeError: module 'arviz' has no attribute 'geweke'

### ISSUE THREAD

**Issue by andrybicio** [rtcovidlive/rtlive-global#19]
When importing pymc3 and following instructions written [here](https://github.com/rtcovidlive/rtlive-global/blob/master/README.md), it results as the following error. 

My OS: Ubuntu 18.04
Python version: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0]

```Python3
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-cbba610deb25> in <module>
      3 
      4 import datetime
----> 5 import pymc3 as pm
      6 import pandas as pd
      7 import pathlib

~/anaconda3/envs/rtlive/lib/python3.8/site-packages/pymc3/__init__.py in <module>
     62 from .sampling import *
     63 from .smc import *
---> 64 from .stats import *
     65 from .step_methods import *
     66 from .tests import test

~/anaconda3/envs/rtlive/lib/python3.8/site-packages/pymc3/stats/__init__.py in <module>
     45 compare = map_args(az.compare)
     46 ess = map_args(az.ess)
---> 47 geweke = map_args(az.geweke)
     48 hpd = map_args(az.hpd)
     49 loo = map_args(az.loo)

AttributeError: module 'arviz' has no attribute 'geweke'
```

I think this is a sort of compatibility issue

**Comment by andrybicio** [comment]
Related to this issue:
 https://discourse.pymc.io/t/attributeerror-module-arviz-has-no-attribute-geweke/6818/4

And solved by using 
`conda install -c conda-forge arviz=0.11.0`

**Comment by michaelosthege** [comment]
The `geweke` statistic was deprecated by ArviZ.

`rtlive-global` is compatible with `pymc3==3.11.2`, so you can also update PyMC3 instead.
