### ISSUE TITLE
National data detail page not working

### ISSUE THREAD

**Issue by davideferre** [rtcovidlive/rtlive-global#20]
Trying to access the detail page for a nation raise a javascript error:
`Uncaught TypeError: Cannot read property 'r_t_threshold_probability' of undefined`

**Comment by michaelosthege** [comment]
@davideferre I can't reproduce it. Where exactly did you observe this?

The repo for the website is here, by the way: https://github.com/michaelosthege/rtlive-dash-de

**Comment by davideferre** [comment]
After a "clear site data" I can't reproduce the issue.
