### ISSUE TITLE
2 of 16 states in germany missing

### ISSUE THREAD

**Issue by cuberick** [rtcovidlive/rtlive-global#21]
Thanks for the great work you guys do!
I noticed that probably the fedaral states Saarland and Bremen are missing.
If this is not intentional, I think people would be happy to have all states.
Thanks a lot! Dirk

**Comment by michaelosthege** [comment]
Hi Dirk,
We'd be happy to have all states too. Unfortunately we don't have testcount data for all of them and it doesn't look like we'll get reliable, machine-readlable and up-to-date testcount data for German states in _this_ pandemic.
We also address more details in the FAQ on the website.
best
michael
